using ParallelProgramming.DataSharingAndSynchronization.Examples.CriticalSections;
using ParallelProgramming.DataSharingAndSynchronization.Examples.InterlockedOperations;
using ParallelProgramming.DataSharingAndSynchronization.Examples.SpinLockingAndLockRecursion;
using ParallelProgramming.DataSharingAndSynchronization.Examples.MutexExample;
using ParallelProgramming.DataSharingAndSynchronization.Examples.ReaderWriterLocks;

CriticalSections.Start(args);

InterlockedOperations.Start(args);

SpinLockingAndLockRecursion.Start(args);

MutexExample.Start(args);

ReaderWriterLocks.Start(args);