using ParallelProgramming.DataSharingAndSynchronization.Examples.CriticalSections;
using ParallelProgramming.DataSharingAndSynchronization.Examples.InterlockedOperations;

CriticalSections.Start(args);

InterlockedOperations.Start(args);